name = "db"                        # Worker 名称
main = "functions/worker.js"       # 你的 Worker 脚本文件
account_id = "ad3a38e4e4cba364bc119216eda22dd8"
workers_dev = true                  # 开启 workers.dev 子域名
